spring.application.name=sportverse-backend
# Twilio Configuration
twilio.account.sid=${TWILIO_ACCOUNT_SID}
twilio.auth.token=${TWILIO_AUTH_TOKEN}
twilio.verification.service.sid=${TWILIO_VERIFICATION_SERVICE_SID}

# MongoDB
mongo.connection-string=${MONGO_CONNECTION_STRING}

# Razorpay Configuration
razorpay.key_id=${RAZORPAY_KEY_ID}
razorpay.key_secret=${RAZORPAY_KEY_SECRET}

# ImageKit Configuration
imagekit.url_endpoint=${IMAGEKIT_URL_ENDPOINT}
imagekit.public_key=${IMAGEKIT_PUBLIC_KEY}
imagekit.private_key=${IMAGEKIT_PRIVATE_KEY}

# WhatsApp Cloud API Configuration
whatsapp.cloud.graph-api-version=v21.0
whatsapp.cloud.phone-number-id=
whatsapp.cloud.access-token=
whatsapp.cloud.webhook-verify-token=m61FZCMaeWCKD8QsQw3Q