spring.application.name=sportverse-backend
# Twilio Configuration
twilio.account.sid=ACdabe2fcb6f64fb36ea1b528dc9a02d2f
twilio.auth.token=8ccf574a005fe568903c61d4fdf3bd85
twilio.verification.service.sid=VAe46c703e99ae5d8b412b44e618e50e3b

# MongoDB
mongo.connection-string=mongodb+srv://abhijitshankhdhar_db_user:VJwW0Kmlu7nIEOIZ@sportverse-cluster.ts3e8l1.mongodb.net/?appName=sportverse-cluster

# Razorpay Configuration
razorpay.key_id=rzp_live_RZFXW0wHz2XukW
razorpay.key_secret=OLQNEQReW35KTYtGedE3yupB
server.port=8087

# ImageKit Configuration
imagekit.url_endpoint=xxx
imagekit.public_key=xxx
imagekit.private_key=xxx
